sudo: required

language: generic

services:
  - docker

script:
  - docker build -t factlist/factlst-api:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push factlist/factlist-api;
    fi